;;;; sketch.lisp

(in-package #:sketch)

;;; "sketch" goes here. Hacks and glory await!

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;                                                                  ;;;
;;;     _|_|_|  _|    _|  _|_|_|_|  _|_|_|_|_|    _|_|_|  _|    _|   ;;;
;;;   _|        _|  _|    _|            _|      _|        _|    _|   ;;;
;;;     _|_|    _|_|      _|_|_|        _|      _|        _|_|_|_|   ;;;
;;;         _|  _|  _|    _|            _|      _|        _|    _|   ;;;
;;;   _|_|_|    _|    _|  _|_|_|_|      _|        _|_|_|  _|    _|   ;;;
;;;                                                                  ;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;;; Sketch class

(defparameter *sketch* nil
  "The current sketch instance.")

(defparameter *default-width* 400
  "The default width of sketch window")
(defparameter *default-height* 400
  "The default height of sketch window")

(defclass sketch ()
  ((%env :initform (make-env) :reader sketch-%env)
   (%setup-called :initform nil :accessor sketch-%setup-called)
   (%viewport-changed :initform t)
   (%entities :initform (make-hash-table) :accessor sketch-%entities)
   (%window :initform nil :accessor sketch-%window :initarg :window)
   (%delayed-init-funs :initform (make-array 0 :adjustable t :fill-pointer t)
                       :accessor sketch-%delayed-init-funs)
   (%noise-seed :initform 7 :accessor sketch-%noise-seed)
   (%noise-map :initform (make-hash-table) :accessor sketch-%noise-map)
   (%noise-lod :initform 4 :accessor sketch-%noise-lod)
   (%noise-falloff :initform 0.5 :accessor sketch-%noise-falloff)
   (%post-init-hooks :initform nil :initarg :post-init-hooks
                     :accessor sketch-%post-init-hooks)
   (%post-draw-hooks :initform nil :initarg :post-draw-hooks
                     :accessor sketch-%post-draw-hooks)
   (%copy-pixels-post-setup-hooks :initform nil :initarg :copy-pixels-post-setup-hooks
                                  :accessor sketch-%copy-pixels-post-setup-hooks)
   (%close-hooks :initform nil :initarg :close-hooks
                 :accessor sketch-%close-hooks)
   (title :initform "Sketch" :accessor sketch-title :initarg :title)
   (width :initform *default-width* :accessor sketch-width :initarg :width)
   (height :initform *default-height* :accessor sketch-height :initarg :height)
   (fullscreen :initform nil :accessor sketch-fullscreen :initarg :fullscreen)
   (resizable :initform nil :accessor sketch-resizable :initarg :resizable)
   (copy-pixels :initform nil :accessor sketch-copy-pixels :initarg :copy-pixels)
   (y-axis :initform :down :accessor sketch-y-axis :initarg :y-axis)
   (close-on :initform :escape :accessor sketch-close-on :initarg :close-on)
   (restart-on-change :initform t :accessor sketch-restart-on-change
                      :initarg :restart-on-change)
   (restart-on :initform :f1 :accessor sketch-restart-on :initarg :restart-on)))

(defun call-hooks (sketch hooks-sym)
  (loop for hook in (slot-value sketch hooks-sym)
        do (funcall hook sketch)))

(defclass sketch-window (kit.sdl2:gl-window)
  ((%sketch
    :initarg :sketch
    :accessor %sketch
    :documentation "The sketch associated with this window.")
   (%closing :initform nil :accessor window-%closing)))

;; Always enabled
(defmethod kit.sdl2:render-enabled ((window sketch-window))
  t)

;; So don't do anything on SETF as well
(defmethod (setf kit.sdl2:render-enabled) (value (window sketch-window))
  value)

 ;;; Non trivial sketch writers

(defmacro define-sketch-writer (slot &body body)
  `(defmethod (setf ,(alexandria:symbolicate 'sketch- slot)) :after (value (instance sketch))
     (alexandria:when-let (win (sketch-%window instance))
       (let ((win (kit.sdl2:sdl-window win)))
         (declare (ignorable win))
         ,@body))))

(define-sketch-writer title
  (sdl2:set-window-title win value))

(define-sketch-writer width
  (sdl2:set-window-size win value (sketch-height instance))
  (initialize-view-matrix instance))

(define-sketch-writer height
  (sdl2:set-window-size win (sketch-width instance) value)
  (initialize-view-matrix instance))

(define-sketch-writer fullscreen
  (sdl2:set-window-fullscreen win value))

(define-sketch-writer resizable
  (sdl2-ffi.functions:sdl-set-window-resizable
   win
   (if value sdl2-ffi:+true+ sdl2-ffi:+false+)))

(define-sketch-writer y-axis
  (initialize-view-matrix instance))

(define-sketch-writer copy-pixels
  (initialize-fbo instance))

;;; Generic functions

(defgeneric prepare (instance &key &allow-other-keys)
  (:documentation "Generated by DEFSKETCH."))

(defgeneric set-tweakable-slots (instance &key &allow-other-keys)
  (:documentation "Generated by DEFSKETCH."))

(defgeneric setup (instance &key &allow-other-keys)
  (:documentation "Called before creating the sketch window.")
  (:method ((instance sketch) &key &allow-other-keys) ()))

(defgeneric draw (instance &key x y width height mode &allow-other-keys)
  (:documentation "Draws the instance with set position, dimensions, and scaling mode.")
  (:method ((instance sketch) &key x y width height mode &allow-other-keys)
    "Called repeatedly after creating the sketch window, 60fps."
    (declare (ignore x y width height mode))
    ()))

(defmethod draw :around ((*sketch* sketch) &key &allow-other-keys)
  (call-next-method)
  (call-hooks *sketch* '%post-draw-hooks))

(defmethod setup :around ((*sketch* sketch) &key &allow-other-keys)
  (call-next-method))

;;; Initialization

(defparameter *initialized* nil)

(defun initialize-sketch ()
  (unless *initialized*
    (setf *initialized* t)
    (kit.sdl2:init)
    (sdl2-ttf:init)
    (sdl2:in-main-thread ()
      (sdl2:gl-set-attr :multisamplebuffers 1)
      (sdl2:gl-set-attr :multisamplesamples 4)

      (sdl2:gl-set-attr :context-major-version 3)
      (sdl2:gl-set-attr :context-minor-version 3)
      (sdl2:gl-set-attr :context-profile-mask 1))))

(defmethod initialize-instance :around ((instance sketch) &key &allow-other-keys)
  (initialize-sketch)
  (sdl2:in-main-thread ()
    (call-next-method))
  (kit.sdl2:start))

(defmethod initialize-instance :after ((instance sketch) &rest initargs &key &allow-other-keys)
  (apply #'prepare instance initargs)
  (setf (sketch-%window instance)
        (make-instance 'sketch-window
                       :title (sketch-title instance)
                       :w (sketch-width instance)
                       :h (sketch-height instance)
                       :fullscreen (sketch-fullscreen instance)
                       :resizable (sketch-resizable instance)
                       :sketch instance))
  (initialize-environment instance)
  (initialize-gl instance)
  ;; These will have been added in the call to PREPARE.
  (with-slots ((fs %delayed-init-funs)) instance
    (loop for f across fs
          do (funcall f))
    (setf fs (make-array 0 :adjustable t :fill-pointer t)))
  (call-hooks instance '%post-init-hooks))

(defmethod update-instance-for-redefined-class :after
    ((instance sketch) added-slots discarded-slots property-list &rest initargs)
  (declare (ignore added-slots discarded-slots property-list))
  (if (sketch-restart-on-change instance)
      (restart-sketch instance initargs)
      (set-tweakable-slots instance)))

(defun restart-sketch (instance initargs)
  (apply #'prepare instance initargs)
  (setf (sketch-%setup-called instance) nil)
  (setf (slot-value instance '%entities) (make-hash-table)))

;;; Error handling

(defun display-error (sketch stage error)
  (background (case stage
                (:setup (rgb 0.4 0.2 0.1))
                (:draw (rgb 0.7 0 0))
                (t (rgb 0 0 0))))
  (with-font (make-error-font)
    (with-identity-matrix
      (text (format nil "Error in ~A~%---~%~a~%---~%Select a restart." stage error)
            20
            (if (= +1 (env-y-axis-sgn *env*))
                20
                (- (sketch-height sketch) 20))))))

;;; Rendering

(defmacro with-sketch ((sketch) &body body)
  `(with-environment (sketch-%env ,sketch)
     (with-pen (make-default-pen)
       (with-font (make-default-font)
         (with-identity-matrix
           ,@body)))))

(defmacro with-gl-draw (&body body)
  `(progn
     (start-draw)
     ,@body
     (end-draw)))

(defun maybe-change-viewport (sketch)
  (with-slots (%env %viewport-changed width height) sketch
    (when %viewport-changed
      (kit.gl.shader:uniform-matrix (env-programs %env) :view-m 4 (vector (env-view-matrix %env)))
      (gl:viewport 0 0 width height)
      (setf %viewport-changed nil))))

(defun copying-pixels-p (sketch)
  (and (sketch-copy-pixels sketch) (env-fbo *env*)))

(defmethod kit.sdl2:render ((win sketch-window) &aux (sketch (%sketch win)))
  (maybe-change-viewport sketch)
  (with-sketch (sketch)
    (with-gl-draw
      (let (stage)
        (macrolet ((with-stage (stage-value &body body)
                     `(progn
                        (setf stage ,stage-value)
                        ,@body
                        (setf stage nil))))
          (handler-bind ((error
                           (lambda (e)
                             (display-error sketch stage e)
                             ;; This is basically copied from the :after method
                             ;; of kit.sdl2:render, as defined in sdl2kit. If
                             ;; we don't do this (flush OpenGL and swap the
                             ;; buffer), then the error message won't be shown
                             ;; in the window. We don't have to worry about the
                             ;; window getting swapped twice, because whatever
                             ;; restart the user picks should skip the :after method.
                             (gl:flush)
                             (sdl2:gl-swap-window
                              (kit.sdl2:sdl-window win)))))
            (when (copying-pixels-p sketch)
              (gl:bind-framebuffer :framebuffer (env-fbo *env*)))
            (unless (sketch-copy-pixels sketch)
              (background (gray 0.4)))
            (when (not (sketch-%setup-called sketch))
              (setf (sketch-%setup-called sketch) t)
              (with-stage :setup
                (setup sketch))
              (when (sketch-copy-pixels sketch)
                (call-hooks sketch '%copy-pixels-post-setup-hooks)))
            (with-stage :draw
              (draw sketch))
            (when (copying-pixels-p sketch) 
              (gl:bind-framebuffer :framebuffer 0)
              (gl:clear-color 0.0 0.0 0.0 1.0)
              (gl:clear :color-buffer)
              (gl:bind-framebuffer :read-framebuffer (env-fbo *env*))
              (gl:bind-framebuffer :draw-framebuffer 0)
              (with-slots (width height) sketch
                (%gl:blit-framebuffer 0 0 width height
                                      0 0 width height
                                      '(:color-buffer-bit)
                                      :nearest))
              (gl:bind-framebuffer :framebuffer 0))))))))

(defmethod kit.sdl2:render :around ((win sketch-window))
  (restart-case (call-next-method)
    (reset-sketch ()
      :report "Start the sketch from scratch."
      (restart-sketch (%sketch win) nil))))

;;; Support for resizable windows

(defmethod kit.sdl2:window-event :before ((instance sketch-window) (type (eql :size-changed)) timestamp data1 data2)
  (with-slots ((sketch %sketch)) instance
    (with-slots ((env %env) width height y-axis) sketch
      (setf width data1
            height data2)
      (initialize-view-matrix sketch)))
  (kit.sdl2:render instance))

;;; Default events

(defconstant +scancode-prefix-length+ (length "scancode-"))

(defun without-sdl2-scancode-prefix (keysym)
  (intern (subseq (symbol-name (sdl2:scancode keysym))
                  +scancode-prefix-length+)
          (find-package "KEYWORD")))

(defmethod kit.sdl2:keyboard-event :before ((instance sketch) state timestamp repeatp keysym)
  (declare (ignorable timestamp repeatp))
  (alexandria:when-let (close-on (sketch-close-on instance))
    (when (and (eql state :keyup)
               (eq (without-sdl2-scancode-prefix keysym) close-on))
      (kit.sdl2:close-window instance)))
  (alexandria:when-let (restart-on (sketch-restart-on instance))
    (when (and (eql state :keyup)
               (eq (without-sdl2-scancode-prefix keysym) restart-on))
      (restart-sketch instance nil))))

(defmethod close-window :before ((instance sketch-window))
  (with-environment (slot-value (%sketch instance) '%env)
    (loop for resource being the hash-values of (env-resources *env*)
       do (free-resource resource))
    (when (env-fbo *env*)
      (gl:delete-framebuffers (vector (env-fbo *env*)))
      (gl:delete-renderbuffers (vector (env-rbo *env*)))
      (setf (env-fbo *env*) nil
            (env-rbo *env*) nil))))

(defmethod close-window :after ((instance sketch))
  (when (and *build* (not (kit.sdl2:all-windows)))
    (sdl2-ttf:quit)
    (kit.sdl2:quit)))

;;; DEFSKETCH macro

(defun define-sketch-defclass (name superclasses bindings)
  `(defclass ,name (sketch ,@superclasses)
     (,@(loop for b in bindings
              unless (eq 'sketch (binding-prefix b))
              collect `(,(binding-name b)
                        :initarg ,(binding-initarg b)
                        :accessor ,(binding-accessor b))))))

(defun define-sketch-channel-observers (bindings)
  (loop for b in bindings
        when (binding-channelp b)
        collect `(define-channel-observer
                   ; TODO: Should this really depend on kit.sdl2?
                   (let ((win (kit.sdl2:last-window)))
                     (when win
                       (setf (,(binding-accessor b) (%sketch win))
                             (in ,(binding-channel-name b)
                                 ,(binding-initform b))))))))

(defun define-sketch-draw-method (name bindings body)
  `(defmethod draw ((*sketch* ,name) &key x y width height mode &allow-other-keys)
     (declare (ignorable x y width height mode))
     (with-accessors (,@(loop for b in bindings
                              collect `(,(binding-name b) ,(binding-accessor b))))
         *sketch*
       ,@body)))

(defun define-sketch-prepare-method (name bindings)
  `(defmethod prepare ((*sketch* ,name)
                       &key ,@(make-all-slots-keyword-list bindings)
                       &allow-other-keys)
     (setf ,@(loop for b in bindings
                   collect `(,(binding-accessor b) *sketch*)
                   collect (binding-name b)))))

(defun define-sketch-set-tweakable-slots (name bindings)
  `(defmethod set-tweakable-slots ((*sketch* ,name)
                                   &key ,@(make-all-slots-keyword-list bindings)
                                   &allow-other-keys)
     (declare (ignorable ,@(mapcar #'binding-name bindings)))
     (setf ,@(loop for b in bindings
                   when (binding-tweakable b)
                     collect `(,(binding-accessor b) *sketch*)
                     and collect (binding-initform b)))))

(defun make-all-slots-keyword-list (bindings)
  (loop for b in bindings
        collect `((,(binding-initarg b) ,(binding-name b))
                  ,(if (binding-defaultp b)
                       `(,(binding-accessor b) *sketch*)
                       (binding-initform b)))))

(defun define-sketch-run-function (name bindings)
  `(defun ,(alexandria:symbolicate 'run- name)
       (&rest args
          &key ,@(loop for b in bindings
                        collect (list (binding-name b) (binding-initform b)))
        &allow-other-keys)
     (declare (ignorable ,@(loop for b in bindings collect (binding-name b))))
     (apply #'make-instance ',name args)))

(defmacro defsketch (sketch-name binding-forms &body body)
  (multiple-value-bind (options binding-forms)
      (extract-options binding-forms)
    (make-defsketch sketch-name
                    (getf options :mixins)
                    binding-forms
                    body)))

(defun sketch-slot-value (slot-sym)
  (slot-value *sketch* slot-sym))

;;; To be able to set the slots of the currently bound sketch
;;; class without needing a reference to it.
(defun (setf sketch-slot-value) (val slot-sym)
  (setf (slot-value *sketch* slot-sym) val))

(defun extract-options (binding-forms)
  (let (options)
    (loop for form in binding-forms
          if (keywordp (car form))
            do (progn
                 (push (cdr form) options)
                 (push (car form) options))
          else collect form into the-rest
          finally (return (values options the-rest)))))

(defun make-defsketch (sketch-name superclasses binding-forms body)
  (let ((bindings (parse-bindings sketch-name binding-forms
                                  (class-bindings (find-class 'sketch)))))
    `(progn
       ,(define-sketch-defclass sketch-name superclasses bindings)
       ,@(define-sketch-channel-observers bindings)
       ,(define-sketch-prepare-method sketch-name bindings)
       ,(define-sketch-set-tweakable-slots sketch-name bindings)
       ,(define-sketch-draw-method sketch-name bindings body)
       ,(define-sketch-run-function sketch-name bindings)

       (make-instances-obsolete ',sketch-name)
       (find-class ',sketch-name))))

(defun run-sketch (name &rest args)
  (let ((cls (find-class name nil)))
    (when (or (null cls)
              (not (c2mop:subclassp cls (find-class 'sketch))))
      (error (format nil "Couldn't find a sketch called ~a" name)))
    (apply #'make-instance name args)))

(defun record-sketch (name output-path
                      &key args frames seconds
                        close-on-finish (fps 60)
                      &allow-other-keys)
  (when (uiop:file-exists-p output-path)
    (error (format nil "File '~a' already exists!" output-path)))
  (handler-case (uiop:run-program "ffmpeg -h")
    (t (c)
      (declare (ignore c))
      (error "ffmpeg doesn't seem to be available on this system.")))
  (let (buffer
        proc
        stream
        done
        (n 0)
        (start (get-universal-time)))
    (labels ((post-init (sketch)
               (setf buffer
                     (static-vectors:make-static-vector
                      (* 4 (sketch-width sketch) (sketch-height sketch))))
               (setf proc
                     (uiop:launch-program
                      (list "ffmpeg"
                            "-r" (format nil "~a" fps)
                            "-f" "rawvideo"
                            "-pix_fmt" "rgba"
                            "-s:v" (format nil "~ax~a"
                                           (sketch-width sketch)
                                           (sketch-height sketch))
                            "-i" "pipe:"
                            "-vf" "vflip"
                            output-path)
                      :input :stream
                      :external-format :latin1
                      :output :interactive
                      :error-output :output))
               (setf stream (uiop:process-info-input proc)))

             (end-recording (sketch)
               (declare (ignore sketch))
               (static-vectors:free-static-vector buffer)
               (uiop:close-streams proc)
               (uiop:wait-process proc))

             (save-frame (sketch)
               (when (not done)
                 (%gl:read-pixels 0 0 (sketch-width sketch) (sketch-height sketch)
                                  :rgba :unsigned-byte
                                  (static-vectors:static-vector-pointer buffer))
                 (write-sequence buffer stream)
                 (incf n)))

             (post-draw (sketch)
               (when (not done)
                 (save-frame sketch)
                 (when (or (and frames (>= n frames))
                           (and seconds (>= (- (get-universal-time) start) seconds)))
                   (setf done t)
                   (if close-on-finish
                       ;; END-RECORDING will be called as part of a hook here, don't
                       ;; need to call it ourselves.
                       (kit.sdl2:close-window sketch)
                       (end-recording sketch))))))

      (apply #'make-instance
             name
             (append args
                     (list :post-init-hooks (list #'post-init)
                           :post-draw-hooks (list #'post-draw)
                           :copy-pixels-post-setup-hooks (list #'save-frame)
                           :close-hooks (list #'end-recording)))))))

;;; Control flow

(defun stop-loop ()
  (setf (sdl2.kit:idle-render (sketch-%window *sketch*)) nil))

(defun start-loop ()
  (setf (sdl2.kit:idle-render (sketch-%window *sketch*)) t))

;;; Backward compatibility.
;; Previously, the main `sketch` class inherited from
;; `kit.sdl2:gl-window`, and input was handled by specialising on methods from
;; sdl2kit. So we need to forward sdl2kit input calls to the `sketch` class for
;; old sketches that rely on that approach.
(defmacro define-sdl2-forward (name (&rest args) &optional already-defined?)
  `(progn
     ;; An empty method so we don't get an error if we try to forward
     ;; when the user hasn't defined it.
     (defmethod ,name ((w sketch) ,@args))
     ,@(when (not already-defined?)
         `((defmethod ,name ((w sketch-window) ,@args)
             (,name (%sketch w) ,@args)
             (call-next-method))))))
(define-sdl2-forward kit.sdl2:mousebutton-event (state timestamp button x y) t)
(define-sdl2-forward kit.sdl2:mousemotion-event (timestamp button-mask x y xrel yrel) t)
(define-sdl2-forward kit.sdl2:textinput-event (timestamp text))
(define-sdl2-forward kit.sdl2:keyboard-event (state timestamp repeatp keysym))
(define-sdl2-forward kit.sdl2:mousewheel-event (timestamp x y))
(define-sdl2-forward kit.sdl2:window-event (type timestamp data1 data2))
(define-sdl2-forward kit.sdl2:controller-added-event (c))
(define-sdl2-forward kit.sdl2:controller-removed-event (c))
(define-sdl2-forward kit.sdl2:controller-axis-motion-event (controller timestamp axis value))
(define-sdl2-forward kit.sdl2:controller-button-event (controller state timestamp button))

(defmethod kit.sdl2:idle-render ((instance sketch))
  (kit.sdl2:idle-render (sketch-%window instance)))

(defmethod (setf kit.sdl2:idle-render) (value (instance sketch))
  (setf (kit.sdl2:idle-render (sketch-%window instance)) value))

(defmethod kit.sdl2:sdl-window ((instance sketch))
  (kit.sdl2:sdl-window (sketch-%window instance)))

(defmethod kit.sdl2:gl-context ((instance sketch))
  (kit.sdl2:gl-context (sketch-%window instance)))

(defmethod kit.sdl2:render-enabled ((instance sketch))
  (kit.sdl2:render-enabled (sketch-%window instance)))

(defmethod (setf kit.sdl2:render-enabled) (value (instance sketch))
  (setf (kit.sdl2:render-enabled (sketch-%window instance)) value))

;; KIT.SDL2:CLOSE-WINDOW is tricky: it should always be called on both
;; the sketch and sketch's window; but it also can be first called on
;; both the window or the sketch.
;; It also should be called in sdl2's main thread, which is done by an
;; :AROUND method defined on KIT.SDL2:WINDOW.
;; The primary method defined on the SKETCH-WINDOW should
;; (call-next-method) because there is a primary method defined on
;; GL-WINDOW.
;; Finally, the :AFTER method defined on SKETCH calls KIT.SDL2:QUIT and
;; SDL2-TTF:QUIT.
(defmethod kit.sdl2:close-window ((instance sketch))
  (with-slots ((window %window)) instance
    (setf (window-%closing window) t)
    (kit.sdl2:close-window window))
  (call-hooks instance '%close-hooks))

(defmethod kit.sdl2:close-window :around ((instance sketch-window))
  (if (window-%closing instance)
      (call-next-method)
      (kit.sdl2:close-window (%sketch instance))))

;;; Resource-handling

(defun delay-init-p ()
  "This checks whether the OpenGL context has been created yet. If not,
we need to wait before initializing certain resources."
  (and *sketch*
       (null (sketch-%window *sketch*))))

(defun add-delayed-init-fun! (f)
  "F should be a function with no arguments."
  (vector-push-extend f (sketch-%delayed-init-funs *sketch*)))
